apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    uid: postgres
    url: postgres:5432
    database: llm_project
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      postgresVersion: 1200
      timescaledb: false
    isDefault: true
    version: 1
    editable: true
